"""MCP server exposing retrieval-augmented search/answering over the Qdrant
collection populated by ../ingest (services/ingest).

Pipeline for both tools:
  1. embed the query with MODEL_EMBED (same model used at ingest time,
     so query and document vectors live in the same space)
  2. fetch TOP_K_RETRIEVE nearest chunks from Qdrant
  3. rerank those candidates via the standalone reranker HTTP service (see
     /services/reranker) and keep the top TOP_K_RERANK -- skippable via
     config.yml's search_tools.reranker.enabled
  4. `answer_question` additionally feeds the reranked chunks as context to a
     generation backend and returns its generated answer. The backend is
     selected by config.yml's search_tools.backend.type:
       - "" : generation is skipped -- answer_question returns retrieved
         context only, same as search_documents.
       - "ollama" (default): the local MODEL_INSTRUCT_INTERNAL via Ollama's
         /api/chat.
       - "anthropic_token": the Claude Messages API (MODEL_INSTRUCT_EXTERNAL,
         e.g. claude-sonnet-5) via the official `anthropic` SDK, using
         ANTHROPIC_API_KEY -- billed per token (see libs/anthropic.py).
       - "anthropic_subscription": the same model, but generated by shelling
         out to the headless `claude` CLI (Claude Code, non-interactive
         mode) using CLAUDE_CODE_OAUTH_TOKEN -- billed against a Claude
         subscription instead of a token balance. This is a genuinely
         different mechanism from anthropic_token, not just a different
         credential on the same SDK call -- see libs/claude_cli.py's
         docstring for why the Messages API itself has no subscription-
         billed mode.
     Thinking is left off for anthropic_token (system prompt already asks
     for a direct, ungrounded-guess-free answer) so latency stays comparable
     to the Ollama path; anthropic_subscription's CLI manages that itself.

A third, independent tool -- `anthropic_chat` -- sends raw text straight to
Claude with no retrieval/RAG context at all, for ad-hoc use outside the
knowledge-base pipeline. It's gated by config.yml's anthropic_chat.enabled
and has its own model/max_tokens/auth (token or subscription), separate from
search_tools.backend.type above -- the two can point at different Claude models and
different credentials, since they're unrelated use cases that just happen to
share the same build_client()/generate() functions in libs/anthropic.py.

Both search_documents/answer_question return structured JSON rather than
plain text: the retrieved chunks (the local data the reasoning is grounded in), the reasoning itself
(`answer_question` only -- see config.yml's search_tools.system_prompt for the Reasoning/
Answer/Sources format, which every generation backend follows since it's
shared), and a `trace` of pipeline steps with wall-clock timings. This is
meant to be consumed by a thin presentation layer (e.g. a Haiku-model agent)
rather than reasoned about further -- the reasoning already happened here.

Exposed over streamable-http so it can be added as a remote MCP connector in
both Open WebUI and Claude (Console / Desktop / claude.ai).

This file is handlers + wiring only. Everything else -- config schema,
retrieval, timing, answer parsing, and the Ollama/Anthropic backend calls --
lives in libs/. Env vars and config.yml are read *only* here; every libs/
function takes what it needs as arguments instead of reading globals itself.
"""

from __future__ import annotations

import functools
from pathlib import Path

from environs import Env
from mcp.server.fastmcp import FastMCP
from opentelemetry.trace import format_trace_id
from qdrant_client import QdrantClient

from _common.logging_config import configure_logging, get_logger
from _common.ollama import build_client, embed_query
from _common.tracing import OTEL_EXPORTER_OTLP_ENDPOINT, configure_tracing, get_meter, get_tracer

from .libs import anthropic as anthropic_lib
from .libs import claude_cli as claude_cli_lib
from .libs import ollama as ollama_lib
from .libs.config import MCPServerConfig, load_config, parse_structured_answer
from .libs.reranker import RerankerClient
from .libs.retrieval import retrieve
from .libs.timer import StepTimer

# env.str(name)/env.int(name) raise a clear environs.EnvError if the
# variable is unset -- no hand-rolled required-env-var helper (that used to
# be copy-pasted between this file and services/ingest/ingest.py).
env = Env()

# config.yml is loaded before most env vars below so search_tools.backend.
# type/anthropic_chat.enabled (both raw, unvalidated at this point) can
# decide which env vars are actually required -- MODEL_INSTRUCT_INTERNAL and
# ANTHROPIC_API_KEY are each only needed by *some* backend.type/
# anthropic_chat.auth combinations, not unconditionally.
raw_config = load_config(Path("config.yml"))
backend_type = raw_config.raw.get("search_tools", {}).get("backend", {}).get("type")

QDRANT_URL = env.str("QDRANT_URL")
QDRANT_COLLECTION = env.str("QDRANT_COLLECTION")
OLLAMA_BASE_URL = env.str("OLLAMA_BASE_URL")
MODEL_EMBED = env.str("MODEL_EMBED")
MCP_HOST = env.str("MCP_HOST")
MCP_PORT = env.int("MCP_PORT")
# Generation model, one env var per search_tools.backend.type: MODEL_INSTRUCT_INTERNAL
# (Ollama) is required only when backend.type is actually "ollama" -- an
# anthropic_token/anthropic_subscription-only deployment doesn't need to
# pull/run a local reasoning model at all (see services/ollama-pull, which
# skips the pull instead of failing when this is unset). MODEL_INSTRUCT_
# EXTERNAL (either anthropic_* variant) is only required when backend.type
# starts with "anthropic" -- BackendConfig's model_validator enforces that
# once the right one is picked and injected below.
MODEL_INSTRUCT_INTERNAL = (
    env.str("MODEL_INSTRUCT_INTERNAL") if backend_type == "ollama" else env.str("MODEL_INSTRUCT_INTERNAL", default=None)
)
MODEL_INSTRUCT_EXTERNAL = env.str("MODEL_INSTRUCT_EXTERNAL", default=None)
# anthropic_chat's model, independent of the two above -- only required
# when anthropic_chat.enabled is true (AnthropicChatConfig's model_validator
# enforces that once injected below).
MODEL_CHAT = env.str("MODEL_CHAT", default=None)

configure_logging()
logger = get_logger(__name__)

configure_tracing("mcp-server")
tracer = get_tracer(__name__)
_requests_counter = get_meter(__name__).create_counter(
    "rag_requests_total", description="RAG tool calls, by tool and outcome."
)

# RAG-pipeline tuning knobs (reranker on/off, retrieval top-k, generation
# backend.type/max_tokens, system prompt, anthropic_chat) live in
# config.yml, not the environment -- see that file for the full field
# reference. It's bind-mounted alongside this package, so editing it just
# needs a restart, not a rebuild. Neither search_tools.backend.model nor
# anthropic_chat.model are meaningful in config.yml itself -- the former is
# picked from MODEL_INSTRUCT_INTERNAL/MODEL_INSTRUCT_EXTERNAL by
# search_tools.backend.type, the latter from MODEL_CHAT, both injected here
# before validating. load_config()/.validate() report/exit on a missing
# file or a schema violation themselves, so there's nothing to catch here.
raw_config.raw["search_tools"]["backend"]["model"] = (
    MODEL_INSTRUCT_EXTERNAL if isinstance(backend_type, str) and backend_type.startswith("anthropic") else MODEL_INSTRUCT_INTERNAL
)
raw_config.raw["anthropic_chat"]["model"] = MODEL_CHAT
config: MCPServerConfig = raw_config.validate(MCPServerConfig)

# ANTHROPIC_API_KEY and CLAUDE_CODE_OAUTH_TOKEN are the two credentials that
# stay in the environment instead of config.yml -- each required (and only
# read) when something actually selects its auth mode. ANTHROPIC_API_KEY:
# backend.type == "anthropic_token", or anthropic_chat enabled with
# auth: "token" (read here, passed to libs/anthropic.py's build_client()).
# CLAUDE_CODE_OAUTH_TOKEN: backend.type == "anthropic_subscription", or
# anthropic_chat enabled with auth: "subscription" -- NOT read here at all;
# the `claude` CLI subprocess (libs/claude_cli.py) picks it up from its own
# inherited environment. It's validated here anyway (env.str() raising if
# unset) purely so a missing credential fails fast at startup with a clear
# message instead of surfacing as an opaque CLI auth error on first call.
_anthropic_token_needed = config.search_tools.backend.type == "anthropic_token" or (
    config.anthropic_chat.enabled and config.anthropic_chat.auth == "token"
)
ANTHROPIC_API_KEY = env.str("ANTHROPIC_API_KEY") if _anthropic_token_needed else None


def _require_anthropic_api_key() -> str:
    # Narrows ANTHROPIC_API_KEY's str | None type to str for mypy at each
    # call site below -- both are only reached when _anthropic_token_needed
    # was true above, which is exactly when the env var was read instead of
    # defaulting to None, but mypy can't see that correlation across the
    # two separate `if` guards.
    assert ANTHROPIC_API_KEY is not None
    return ANTHROPIC_API_KEY

_claude_subscription_needed = config.search_tools.backend.type == "anthropic_subscription" or (
    config.anthropic_chat.enabled and config.anthropic_chat.auth == "subscription"
)
if _claude_subscription_needed:
    env.str("CLAUDE_CODE_OAUTH_TOKEN")

# RERANKER_URL (a full base URL, e.g. "http://reranker:50051") points at the
# standalone reranker HTTP service -- only read when search_tools.reranker.enabled is
# true in config.yml. The model/max_length that service runs live in *its
# own* config.yml, not here.
RERANKER_URL = env.str("RERANKER_URL") if config.search_tools.reranker.enabled else None

qdrant = QdrantClient(url=QDRANT_URL)
ollama_client = build_client(OLLAMA_BASE_URL, config.search_tools.ollama_timeout)
reranker_client = RerankerClient(RERANKER_URL) if RERANKER_URL else None

# answer_question's SDK generation client -- built only for backend.type ==
# "anthropic_token". anthropic_subscription has no client object: it calls
# libs/claude_cli.py's generate() directly (a subprocess, not an SDK call).
anthropic_client = (
    anthropic_lib.build_client(_require_anthropic_api_key())
    if config.search_tools.backend.type == "anthropic_token"
    else None
)

# anthropic_chat tool's SDK client -- independent of the RAG backend above
# (see AnthropicChatConfig's docstring in libs/config.py), built only when
# enabled with auth: "token". auth: "subscription" likewise has no client
# object -- see anthropic_client above.
anthropic_chat_client = (
    anthropic_lib.build_client(_require_anthropic_api_key())
    if config.anthropic_chat.enabled and config.anthropic_chat.auth == "token"
    else None
)

# Bound once so handlers don't need to know which embedding provider is
# configured -- currently always Ollama, but this is the seam if that ever
# changes.
_embed_fn = functools.partial(embed_query, ollama_client, MODEL_EMBED)

mcp = FastMCP("rag", host=MCP_HOST, port=MCP_PORT)


@mcp.tool()
def search_documents(
    query: str,
    top_k: int = config.search_tools.retrieval.top_k_rerank,
    title: str | None = None,
    description: str | None = None,
    source_path: str | None = None,
) -> dict:
    """Search the RAG knowledge base and return the most relevant document
    chunks, ranked by a cross-encoder reranker. Query can be in Russian or
    English. Use this when you want the raw source excerpts yourself rather
    than a synthesized answer.

    Args:
        query: natural-language search query.
        top_k: how many reranked chunks to return.
        title: exact-match filter to a single page's title, if known.
        description: exact-match filter to a single page's front-matter
            description, if known.
        source_path: exact-match filter to a single page's path (as shown in
            results' source_path field), if known.

    Returns a dict:
        results: list of chunk dicts (title, description, source_path,
            heading, text, retrieval_score, rerank_score).
        trace: list of {"step", "duration_ms"} for each pipeline stage
            (embed_query, qdrant_search, rerank), in call order.
        trace_id: hex OTel trace ID for this call (find it in Tempo/Loki),
            or null if the monitoring stack isn't up.
    """
    with tracer.start_as_current_span("search_documents") as span:
        span.set_attribute("rag.query", query)
        span.set_attribute("rag.top_k", top_k)
        timer = StepTimer()
        try:
            results = retrieve(
                query,
                config.search_tools.retrieval.top_k_retrieve,
                max(1, top_k),
                timer,
                qdrant=qdrant,
                collection=QDRANT_COLLECTION,
                embed_fn=_embed_fn,
                reranker_enabled=config.search_tools.reranker.enabled,
                rerank_fn=reranker_client.rerank if reranker_client else None,
                rerank_confidence_cutoff=config.search_tools.reranker.confidence_cutoff,
                title=title,
                description=description,
                source_path=source_path,
            )
        except Exception:
            _requests_counter.add(1, {"tool": "search_documents", "status": "error"})
            raise
        span.set_attribute("rag.chunks_returned", len(results))
        logger.info(
            "search_documents query=%r top_k=%d chunks=%d selected=%s",
            query,
            top_k,
            len(results),
            [
                {
                    "title": c["title"],
                    "source_path": c["source_path"],
                    "heading": c["heading"],
                    "retrieval_score": c["retrieval_score"],
                    "rerank_score": c["rerank_score"],
                }
                for c in results
            ],
        )
        _requests_counter.add(1, {"tool": "search_documents", "status": "ok"})
        trace_id = format_trace_id(span.get_span_context().trace_id) if OTEL_EXPORTER_OTLP_ENDPOINT else None
        return {"results": results, "trace": timer.trace, "trace_id": trace_id}


@mcp.tool()
def answer_question(
    query: str,
    top_k: int = config.search_tools.retrieval.top_k_rerank,
    title: str | None = None,
    description: str | None = None,
    source_path: str | None = None,
) -> dict:
    """Answer a question by retrieving relevant chunks from the RAG knowledge
    base, reranking them, and -- if config.yml's search_tools.backend.type is set --
    asking that generation backend (local Ollama, or the Claude API) to
    compose an answer grounded in that context. Query can be in Russian or
    English; the answer is returned in the same language as the query.

    If backend.type is empty (""), no generation happens: this behaves like
    search_documents, returning only context/trace with answer/reasoning/
    sources left null/empty -- use this mode to skip generation latency/cost
    when you just want the retrieved chunks via this tool's response shape.

    The reasoning behind the answer (when generation runs) is already
    produced by the pipeline (see config.yml's search_tools.system_prompt) -- callers
    should present `reasoning`/`trace` as-is rather than re-deriving them.

    Args:
        query: the user's question.
        top_k: how many reranked chunks to use as context.
        title: exact-match filter to a single page's title, if known.
        description: exact-match filter to a single page's front-matter
            description, if known.
        source_path: exact-match filter to a single page's path (as shown in
            context's source_path field), if known.

    Returns a dict:
        answer: the answer text; a "not found" message if no chunks matched;
            or null if backend.type is "" (generation skipped).
        reasoning: the model's stated reasoning for the answer, or null if
            no chunks matched, generation was skipped, or the model didn't
            follow the expected format.
        sources: list of source strings the model cited, or [].
        context: the chunk dicts (same shape as search_documents' `results`)
            the answer was grounded in -- the local data behind `reasoning`.
        input_tokens: tokens consumed by the generate step, or null if no
            chunks matched or backend.type is "" (generation skipped).
            Always 0 for backend.type: "ollama" -- token accounting isn't
            tracked for that backend, by design.
        output_tokens: same as input_tokens, for the generated reply.
        trace: list of {"step", "duration_ms"} for each pipeline stage
            (embed_query, qdrant_search, rerank, generate), in call order.
            "generate" is absent when backend.type is "".
        trace_id: hex OTel trace ID for this call (find it in Tempo/Loki),
            or null if the monitoring stack isn't up.
    """
    with tracer.start_as_current_span("answer_question") as span:
        span.set_attribute("rag.query", query)
        span.set_attribute("rag.top_k", top_k)
        span.set_attribute("rag.backend_type", config.search_tools.backend.type)
        trace_id = format_trace_id(span.get_span_context().trace_id) if OTEL_EXPORTER_OTLP_ENDPOINT else None
        timer = StepTimer()
        try:
            chunks = retrieve(
                query,
                config.search_tools.retrieval.top_k_retrieve,
                max(1, top_k),
                timer,
                qdrant=qdrant,
                collection=QDRANT_COLLECTION,
                embed_fn=_embed_fn,
                reranker_enabled=config.search_tools.reranker.enabled,
                rerank_fn=reranker_client.rerank if reranker_client else None,
                rerank_confidence_cutoff=config.search_tools.reranker.confidence_cutoff,
                title=title,
                description=description,
                source_path=source_path,
            )
        except Exception:
            _requests_counter.add(1, {"tool": "answer_question", "status": "error"})
            raise
        span.set_attribute("rag.chunks_returned", len(chunks))

        if not chunks:
            logger.info("answer_question query=%r -- no chunks matched", query)
            _requests_counter.add(1, {"tool": "answer_question", "status": "no_chunks"})
            return {
                "answer": "No relevant documents were found in the knowledge base for this query.",
                "reasoning": None,
                "sources": [],
                "context": [],
                "input_tokens": None,
                "output_tokens": None,
                "trace": timer.trace,
                "trace_id": trace_id,
            }

        if not config.search_tools.backend.type:
            _requests_counter.add(1, {"tool": "answer_question", "status": "ok"})
            return {
                "answer": None,
                "reasoning": None,
                "sources": [],
                "context": chunks,
                "input_tokens": None,
                "output_tokens": None,
                "trace": timer.trace,
                "trace_id": trace_id,
            }

        context = "\n\n".join(
            config.search_tools.source_template.format(
                id=i, title=c["title"], path=c["source_path"], updated=c["updated"] or "unknown", text=c["text"]
            )
            for i, c in enumerate(chunks, start=1)
        )
        user_content = config.search_tools.user_prompt_template.format(context=context, query=query)

        with timer("generate"):
            match config.search_tools.backend.type:
                case "anthropic_token":
                    # Guaranteed non-None by this point: anthropic_client is
                    # built whenever backend.type is "anthropic_token", and
                    # BackendConfig's model_validator requires model/
                    # max_tokens in that case too -- mypy can't see either
                    # invariant from here.
                    assert anthropic_client is not None
                    assert config.search_tools.backend.model is not None
                    assert config.search_tools.backend.max_tokens is not None
                    span.set_attribute("rag.model", config.search_tools.backend.model)
                    result = anthropic_lib.generate(
                        anthropic_client,
                        config.search_tools.backend.model,
                        config.search_tools.backend.max_tokens,
                        config.search_tools.system_prompt,
                        user_content,
                    )
                case "anthropic_subscription":
                    # No client object here -- this shells out to the
                    # `claude` CLI (see libs/claude_cli.py's docstring for
                    # why subscription billing needs a different mechanism
                    # than the SDK's Messages API calls above).
                    assert config.search_tools.backend.model is not None
                    span.set_attribute("rag.model", config.search_tools.backend.model)
                    result = claude_cli_lib.generate(
                        config.search_tools.backend.model,
                        config.search_tools.system_prompt,
                        user_content,
                        config.search_tools.generate_timeout,
                    )
                case "ollama":
                    # MODEL_INSTRUCT_INTERNAL is a required env var when
                    # backend.type is "ollama" (server.py module scope),
                    # injected into backend.model -- guaranteed non-None here.
                    assert config.search_tools.backend.model is not None
                    span.set_attribute("rag.model", config.search_tools.backend.model)
                    result = ollama_lib.generate(ollama_client, config.search_tools.backend.model, config.search_tools.system_prompt, user_content, config.search_tools.generate_timeout)
                case _:
                    # Unreachable: config.search_tools.backend.type is a pydantic Literal
                    # ("", "ollama", "anthropic_token", "anthropic_subscription"),
                    # and "" already returned above.
                    raise AssertionError(f"unhandled backend.type: {config.search_tools.backend.type!r}")

        reasoning, answer, sources = parse_structured_answer(result.text)
        span.set_attribute("rag.input_tokens", result.input_tokens)
        span.set_attribute("rag.output_tokens", result.output_tokens)
        logger.info(
            "answer_question query=%r model=%s chunks=%d selected=%s",
            query,
            config.search_tools.backend.model,
            len(chunks),
            [
                {
                    "title": c["title"],
                    "source_path": c["source_path"],
                    "heading": c["heading"],
                    "retrieval_score": c["retrieval_score"],
                    "rerank_score": c["rerank_score"],
                }
                for c in chunks
            ],
        )
        # Raw pre-parse text -- lets you see exactly what the model said
        # (including whether it followed the Reasoning/Answer/Sources
        # contract at all) even when parse_structured_answer() falls back
        # to reasoning=None because the "Answer:" label was missing/malformed.
        logger.info("answer_question query=%r raw_generation=%s", query, result.text)
        logger.info(
            "answer_question query=%r input_tokens=%d output_tokens=%d reasoning=%s sources=%s\nanswer=%s",
            query,
            result.input_tokens,
            result.output_tokens,
            reasoning,
            sources,
            answer,
        )
        _requests_counter.add(1, {"tool": "answer_question", "status": "ok"})
        return {
            "answer": answer,
            "reasoning": reasoning,
            "sources": sources,
            "context": chunks,
            "input_tokens": result.input_tokens,
            "output_tokens": result.output_tokens,
            "trace": timer.trace,
            "trace_id": trace_id,
        }


# Registered only when config.yml's anthropic_chat.enabled is true, so the
# tool doesn't show up in the MCP tool list (and can't be called into a
# guaranteed RuntimeError) on a deployment that hasn't turned it on.
if config.anthropic_chat.enabled:

    @mcp.tool()
    def anthropic_chat(prompt: str, system_prompt: str | None = None) -> dict:
        """Send raw text directly to Claude and return its reply -- no
        retrieval, no RAG context, unrelated to search_documents/
        answer_question. Model, max_tokens, and auth mode (API token or
        Claude subscription) are set by config.yml's anthropic_chat
        section, independent of backend.type (which only affects
        answer_question's generation step).

        Args:
            prompt: the text to send to Claude.
            system_prompt: optional override for config.yml's
                anthropic_chat.system_prompt.

        Returns a dict:
            text: Claude's reply as plain text.
            input_tokens: tokens consumed by this call.
            output_tokens: tokens generated by this call.
        """
        assert config.anthropic_chat.model is not None
        effective_system_prompt = system_prompt if system_prompt is not None else config.anthropic_chat.system_prompt
        with tracer.start_as_current_span("anthropic_chat") as span:
            span.set_attribute("rag.model", config.anthropic_chat.model)
            try:
                if config.anthropic_chat.auth == "token":
                    # Guaranteed non-None: anthropic_chat_client is built
                    # whenever auth is "token", and AnthropicChatConfig's
                    # model_validator requires max_tokens in that case too.
                    assert anthropic_chat_client is not None
                    assert config.anthropic_chat.max_tokens is not None
                    result = anthropic_lib.generate(
                        anthropic_chat_client,
                        config.anthropic_chat.model,
                        config.anthropic_chat.max_tokens,
                        effective_system_prompt,
                        prompt,
                    )
                else:
                    # No client object -- shells out to the `claude` CLI
                    # (see libs/claude_cli.py's docstring). max_tokens
                    # doesn't apply here, only config.anthropic_chat.timeout.
                    result = claude_cli_lib.generate(
                        config.anthropic_chat.model,
                        effective_system_prompt,
                        prompt,
                        config.anthropic_chat.timeout,
                    )
            except Exception:
                _requests_counter.add(1, {"tool": "anthropic_chat", "status": "error"})
                raise
            span.set_attribute("rag.input_tokens", result.input_tokens)
            span.set_attribute("rag.output_tokens", result.output_tokens)
            _requests_counter.add(1, {"tool": "anthropic_chat", "status": "ok"})
            return {"text": result.text, "input_tokens": result.input_tokens, "output_tokens": result.output_tokens}


# ASGI app entry point, so the container can run this via a plain `uvicorn
# src.server:app` (needed for --reload in dev; mcp.run() drives its own
# uvicorn instance internally and doesn't support that).
app = mcp.streamable_http_app()

if __name__ == "__main__":
    mcp.run(transport="streamable-http")
